-- Insertar datos en la tabla auto
INSERT INTO auto (id, marka, modeloa, auto_foto) VALUES
(1, 'Toyota', 'Corolla', '/auto_fotos/toyota_corolla.jpg'),
(2, 'Volkswagen', 'Golf', '/auto_fotos/vw_golf.jpg'),
(3, 'Ford', 'Focus', '/auto_fotos/ford_focus.jpg'),
(4, 'Renault', 'Clio', '/auto_fotos/renault_clio.jpg'),
(5, 'Mercedes-Benz', 'Clase A', '/auto_fotos/mercedes_a.jpg'),
(6, 'BMW', 'Serie 3', '/auto_fotos/bmw_3.jpg'),
(7, 'Seat', 'Leon', '/auto_fotos/seat_leon.jpg'),
(8, 'Audi', 'A3', '/auto_fotos/audi_a3.jpg'),
(9, 'Nissan', 'Qashqai', '/auto_fotos/nissan_qashqai.jpg'),
(10, 'Toyota', 'Camry', '/auto_fotos/toyota_camry.jpg'),
(11, 'Volkswagen', 'Passat', '/auto_fotos/vw_passat.jpg'),
(12, 'Ford', 'Fiesta', '/auto_fotos/ford_fiesta.jpg'),
(13, 'Renault', 'Megane', '/auto_fotos/renault_megane.jpg'),
(14, 'Mercedes-Benz', 'Clase C', '/auto_fotos/mercedes_c.jpg'),
(15, 'BMW', 'Serie 5', '/auto_fotos/bmw_5.jpg'),
(16, 'Seat', 'Ibiza', '/auto_fotos/seat_ibiza.jpg'),
(17, 'Audi', 'A4', '/auto_fotos/audi_a4.jpg'),
(18, 'Nissan', 'Micra', '/auto_fotos/nissan_micra.jpg'),
(19, 'Toyota', 'RAV4', '/auto_fotos/toyota_rav4.jpg'),
(20, 'Volkswagen', 'Polo', '/auto_fotos/vw_polo.jpg'),
(21, 'Ford', 'Mondeo', '/auto_fotos/ford_mondeo.jpg'),
(22, 'BMW', 'Serie 1', '/auto_fotos/bmw_1.jpg'),
(23, 'Audi', 'Q3', '/auto_fotos/audi_q3.jpg');


-- Insertar datos en la tabla matxura
INSERT INTO matxura (auto_id, deskribapena, foto_ruta, video_ruta) VALUES
(1, 'Fallo en el sistema de frenos', '/fotos/frenos1.jpg', '/videos/frenos1.mp4'),
(1, 'Cambio de aceite necesario', '/fotos/aceite1.jpg', '/videos/aceite1.mp4'),
(2, 'Problemas con el embrague', '/fotos/embrague1.jpg', '/videos/embrague1.mp4'),
(3, 'Fallo en el sistema eléctrico', '/fotos/electrico1.jpg', '/videos/electrico1.mp4'),
(4, 'Ruidos en la suspensión', '/fotos/suspension1.jpg', '/videos/suspension1.mp4'),
(5, 'Pérdida de refrigerante', '/fotos/refrigerante1.jpg', '/videos/refrigerante1.mp4'),
(6, 'Problemas con el turbo', '/fotos/turbo1.jpg', '/videos/turbo1.mp4'),
(7, 'Desgaste de neumáticos irregular', '/fotos/neumaticos1.jpg', '/videos/neumaticos1.mp4'),
(8, 'Fallo en el sensor de oxígeno', '/fotos/sensor1.jpg', '/videos/sensor1.mp4'),
(9, 'Filtro de aire obstruido', '/fotos/filtro1.jpg', '/videos/filtro1.mp4'),
(10, 'Problemas con la dirección asistida', '/fotos/direccion1.jpg', '/videos/direccion1.mp4'),
(11, 'Batería descargada', '/fotos/bateria1.jpg', '/videos/bateria1.mp4'),
(12, 'Fallo en el alternador', '/fotos/alternador1.jpg', '/videos/alternador1.mp4'),
(13, 'Bujías desgastadas', '/fotos/bujias1.jpg', '/videos/bujias1.mp4'),
(14, 'Correa de distribución dañada', '/fotos/correa1.jpg', '/videos/correa1.mp4'),
(15, 'Problemas con el catalizador', '/fotos/catalizador1.jpg', '/videos/catalizador1.mp4'),
(16, 'Fugas de aceite', '/fotos/aceite2.jpg', '/videos/aceite2.mp4'),
(17, 'Problemas con el sistema de escape', '/fotos/escape1.jpg', '/videos/escape1.mp4'),
(18, 'Fallo en el sistema de inyección', '/fotos/inyeccion1.jpg', '/videos/inyeccion1.mp4'),
(19, 'Problemas con el sistema de refrigeración', '/fotos/refrigeracion1.jpg', '/videos/refrigeracion1.mp4'),
(20, 'Fallo en el sistema de suspensión', '/fotos/suspension2.jpg', '/videos/suspension2.mp4'),
(21, 'Problemas con el sistema de frenos antibloqueo', '/fotos/abs1.jpg', '/videos/abs1.mp4'),
(22, 'Fallo en el sistema de control de tracción', '/fotos/traccion1.jpg', '/videos/traccion1.mp4'),
(23, 'Problemas con el sistema de dirección', '/fotos/direccion2.jpg', '/videos/direccion2.mp4'),
(1, 'Fallo en el sistema de climatización', '/fotos/climatizacion1.jpg', '/videos/climatizacion1.mp4'),
(2, 'Problemas con el sistema de audio', '/fotos/audio1.jpg', '/videos/audio1.mp4'),
(3, 'Fallo en el sistema de navegación', '/fotos/navegacion1.jpg', '/videos/navegacion1.mp4'),
(4, 'Problemas con el sistema de luces', '/fotos/luces1.jpg', '/videos/luces1.mp4'),
(5, 'Fallo en el sistema de limpiaparabrisas', '/fotos/limpiaparabrisas1.jpg', '/videos/limpiaparabrisas1.mp4'),
(6, 'Problemas con el sistema de cierre centralizado', '/fotos/cierre1.jpg', '/videos/cierre1.mp4'),
(7, 'Fallo en el sistema de alarma', '/fotos/alarma1.jpg', '/videos/alarma1.mp4');

