-- Insertar datos en la tabla auto
INSERT INTO auto (id, marka, modeloa, auto_foto) VALUES
(1, 'Toyota', 'Corolla', '/images/autoak/toyota-corolla.jpg'),
(2, 'Volkswagen', 'Golf', '/images/autoak/vw_golf.jpg'),
(3, 'Ford', 'Focus', '/images/autoak/ford-focus.jpeg'),
(4, 'Renault', 'Clio', '/images/autoak/Renault_Clio.jpg'),
(5, 'Mercedes-Benz', 'Clase A', '/images/autoak/mercedes_a.jpg'),
(6, 'BMW', 'Serie 3', '/images/autoak/bmw_3.jpg'),
(7, 'Seat', 'Leon', '/images/autoak/seat_leon.jpg'),
(8, 'Audi', 'A3', '/images/autoak/audi_a3.jpg'),
(9, 'Nissan', 'Qashqai', '/images/autoak/nissan_qashqai.jpg'),
(10, 'Toyota', 'Camry', '/images/autoak/toyota_camry.jpg'),
(11, 'Volkswagen', 'Passat', '/images/autoak/vw_passat.jpg'),
(12, 'Ford', 'Fiesta', '/images/autoak/ford_fiesta.jpg'),
(13, 'Renault', 'Megane', '/images/autoak/renault_megane.jpeg'),
(14, 'Mercedes-Benz', 'Clase C', '/images/autoak/Mercedes_C.jpg'),
(15, 'BMW', 'Serie 5', '/images/autoak/bmw_5.jpg'),
(16, 'Seat', 'Ibiza', '/images/autoak/seat_ibiza.jpg'),
(17, 'Audi', 'A4', '/images/autoak/audi_a4.jpg'),
(18, 'Nissan', 'Micra', '/images/autoak/nissan_micra.jpeg'),
(19, 'Toyota', 'RAV4', '/images/autoak/toyota_rav4.jpg'),
(20, 'Volkswagen', 'Polo', '/images/autoak/vw_polo.jpg'),
(21, 'Ford', 'Mondeo', '/images/autoak/ford_mondeo.jpg'),
(22, 'BMW', 'Serie 1', '/images/autoak/bmw_1.jpg'),
(23, 'Audi', 'Q3', '/images/autoak/audi_q3.jpeg');


-- Insertar datos en la tabla matxura
INSERT INTO matxura (auto_id, deskribapena, foto_ruta, video_ruta) VALUES
(1, 'Balazta-sistemaren hutsegitea', '/fotos/frenos1.jpg', '/videos/frenos1.mp4'),
(1, 'Olio aldaketa beharrezkoa', '/fotos/aceite1.jpg', '/videos/aceite1.mp4'),
(2, 'Enbrage arazoak', '/fotos/embrague1.jpg', '/videos/embrague1.mp4'),
(3, 'Sistema elektrikoaren hutsegitea', '/fotos/electrico1.jpg', '/videos/electrico1.mp4'),
(4, 'Esekidura-zaratak', '/fotos/suspension1.jpg', '/videos/suspension1.mp4'),
(5, 'Hoztaile galera', '/fotos/refrigerante1.jpg', '/videos/refrigerante1.mp4'),
(6, 'Turbo arazoak', '/fotos/turbo1.jpg', '/videos/turbo1.mp4'),
(7, 'Pneumatikoen higadura irregularra', '/fotos/neumaticos1.jpg', '/videos/neumaticos1.mp4'),
(8, 'Oxigeno sentsorearen hutsegitea', '/fotos/sensor1.jpg', '/videos/sensor1.mp4'),
(9, 'Aire iragazki buxatua', '/fotos/filtro1.jpg', '/videos/filtro1.mp4'),
(10, 'Direkzio lagunduko arazoak', '/fotos/direccion1.jpg', '/videos/direccion1.mp4'),
(11, 'Bateria deskargatua', '/fotos/bateria1.jpg', '/videos/bateria1.mp4'),
(12, 'Alternadorearen hutsegitea', '/fotos/alternador1.jpg', '/videos/alternador1.mp4'),
(13, 'Bujia higatuak', '/fotos/bujias1.jpg', '/videos/bujias1.mp4'),
(14, 'Banaketa-uhala kaltetua', '/fotos/correa1.jpg', '/videos/correa1.mp4'),
(15, 'Katalizadore arazoak', '/fotos/catalizador1.jpg', '/videos/catalizador1.mp4'),
(16, 'Olio ihesak', '/fotos/aceite2.jpg', '/videos/aceite2.mp4'),
(17, 'Ihes-sistema arazoak', '/fotos/escape1.jpg', '/videos/escape1.mp4'),
(18, 'Injekzio-sistemaren hutsegitea', '/fotos/inyeccion1.jpg', '/videos/inyeccion1.mp4'),
(19, 'Hozte-sistema arazoak', '/fotos/refrigeracion1.jpg', '/videos/refrigeracion1.mp4'),
(20, 'Esekidura-sistemaren hutsegitea', '/fotos/suspension2.jpg', '/videos/suspension2.mp4'),
(21, 'ABS balazta-sistemaren arazoak', '/fotos/abs1.jpg', '/videos/abs1.mp4'),
(22, 'Trakzio-kontrol sistemaren hutsegitea', '/fotos/traccion1.jpg', '/videos/traccion1.mp4'),
(23, 'Direkzio-sistemaren arazoak', '/fotos/direccion2.jpg', '/videos/direccion2.mp4'),
(1, 'Klimatizazio-sistemaren hutsegitea', '/fotos/climatizacion1.jpg', '/videos/climatizacion1.mp4'),
(2, 'Audio-sistema arazoak', '/fotos/audio1.jpg', '/videos/audio1.mp4'),
(3, 'Nabigazio-sistemaren hutsegitea', '/fotos/navegacion1.jpg', '/videos/navegacion1.mp4'),
(4, 'Argi-sistema arazoak', '/fotos/luces1.jpg', '/videos/luces1.mp4'),
(5, 'Haizetako-garbigailuaren hutsegitea', '/fotos/limpiaparabrisas1.jpg', '/videos/limpiaparabrisas1.mp4'),
(6, 'Itxiera zentralizatuaren arazoak', '/fotos/cierre1.jpg', '/videos/cierre1.mp4'),
(7, 'Alarma-sistemaren hutsegitea', '/fotos/alarma1.jpg', '/videos/alarma1.mp4');

